script for scores:
- subdf with the top20 scores
- take mean, weighted mean, multiplication (prod) and add to df
- calculate roc,pr,fr... improve? ja/ nein

TOP20: ['chai_constrained_interface_iptm', 'boltz_template_per_chain_pair_iptm', 'boltz_free_confidence_score', 'boltz_template_iptm', 'esmfold_ptm', 'boltz_free_per_chain_pair_iptm', 'boltz_free_iptm', 'boltz_free_pde', 'boltz_template_confidence_score', 'boltz_free_iplddt', 'boltz_template_iplddt', 'chai_unconstrained_per_chain_iptm', 'boltz_free_plddt', 'boltz_template_ptm', 'chai_unconstrained_ptm', 'cf_ipsae', 'chai_unconstrained_aggregate_score', 'chai_unconstrained_score', 'chai_unconstrained_iptm', 'boltz_free_ptm']

In [5]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path


mcmahon = pd.read_csv("/home/bri/pymol/EDA/static/rankings_mcmahon/rankings.csv")
germinal = pd.read_csv("/home/bri/pymol/EDA/static/rankings_germinal/rankings.csv")
snir = pd.read_csv("/home/bri/pymol/EDA/static/rankings_snir/rankings.csv")

df = pd.concat([germinal, mcmahon, snir], ignore_index=True)
df.to_csv("/home/bri/pymol/EDA/static/rankings_merged.csv", index=False)
OUTPUT_DIR = Path("/home/bri/pymol/EDA/static/top_scores")
OUTPUT_DIR.mkdir(exist_ok=True)

In [10]:
import pandas as pd

df = pd.read_csv("/home/bri/pymol/EDA/static/scores2combine.csv")
df.head(10)

,source,type,binder,KD[M],EC50[M],sample,chai_constrained_ipsae,boltz_template_pdockq,boltz_free_pdockq,chai_constrained_interface_iptm,...,boltz_template_iptm,boltz_free_per_chain_pair_iptm,chai_constrained_lis,boltz_free_confidence_score,boltz_free_iptm,boltz_free_ipsae,chai_unconstrained_ipsae,boltz_free_pde,boltz_template_confidence_score,boltz_template_pdockq2
0,germinal,original,0,NaN,NaN,nb_s413501_mpnn_3_PDL1,0.800253,0.3117,0.0723,0.806765,...,0.639892,0.525352,0.6602,0.797495,0.558640,0.214560,0.350036,0.524040,0.876754,0.2812
1,germinal,original,0,NaN,NaN,nb_s80903_mpnn_4_PDL1,0.706930,0.3215,0.1250,0.683231,...,0.843225,0.833251,0.5909,0.860622,0.833251,0.593958,0.644546,0.367688,0.889832,0.4823
2,germinal,original,0,NaN,NaN,nb_s185784_mpnn_4_PDL1,0.201424,0.2974,0.1291,0.306330,...,0.688911,0.881156,0.2147,0.793620,0.886232,0.751587,0.693046,0.357327,0.830536,0.3102
3,germinal,original,0,NaN,NaN,nb_s465730_mpnn_4_PDL1,0.741140,0.3291,0.1356,0.733525,...,0.845215,0.613210,0.6104,0.777833,0.627241,0.234103,0.596298,0.585393,0.895193,0.5252
4,germinal,original,0,NaN,NaN,nb_s892360_mpnn_4_PDL1,0.263522,0.4001,0.1619,0.389953,...,0.906872,0.757157,0.3084,0.820556,0.790814,0.379661,0.118392,0.443887,0.926922,0.7099
5,germinal,original,0,NaN,NaN,nb_s461534_mpnn_4_PDL1,0.624838,0.2272,0.1057,0.685075,...,0.695417,0.513598,0.5799,0.811136,0.532987,0.138767,0.117649,0.566788,0.886571,0.2691
6,germinal,original,0,NaN,NaN,nb_s1683_mpnn_1_PDL1,0.574826,0.1856,0.0786,0.655350,...,0.811863,0.498121,0.4908,0.783662,0.546006,0.145382,0.113102,0.558148,0.882504,0.4672
7,germinal,original,0,NaN,NaN,nb_s859190_mpnn_1_PDL1,0.607833,0.2003,0.1254,0.682946,...,0.825736,0.636514,0.5574,0.844952,0.661681,0.291636,0.255172,0.507296,0.909711,0.5374
8,germinal,original,0,NaN,NaN,nb_s78562_mpnn_1_PDL1,0.327095,0.3050,0.1094,0.430920,...,0.858519,0.485501,0.3680,0.806109,0.518422,0.145844,0.845233,0.621077,0.929375,0.7446
9,germinal,original,0,NaN,NaN,nb_s351880_mpnn_3_PDL1,0.361680,0.4876,0.4432,0.436881,...,0.584594,0.854142,0.4030,0.889229,0.857892,0.639780,0.423760,0.366474,0.855112,0.1259

In [ ]:
# normalize scores to 0-1 range (higher = better) --> actually not that good
# use standard scaler

from sklearn.preprocessing import StandardScaler
cols_to_combine = ['chai_constrained_ipsae', 'boltz_template_pdockq'] # they are both between 0-1 --> not necessary, but we can do standard scaling to center them around 0 and have unit variance

# standard scaler
scaler = StandardScaler()
df_norm = pd.DataFrame(scaler.fit_transform(df[cols_to_combine]), columns=cols_to_combine)

df_norm.head()

   chai_constrained_ipsae  boltz_template_pdockq
0                0.921917               0.512159
1                0.809159               0.528262
2                0.198382               0.488663
3                0.850494               0.540749
4                0.273412               0.657410

In [ ]:
# Mean
df['Mean_Score'] = df_norm.mean(axis=1)

df.head()

,source,type,binder,KD[M],EC50[M],sample,chai_constrained_ipsae,boltz_template_pdockq,boltz_free_pdockq,chai_constrained_interface_iptm,...,boltz_free_per_chain_pair_iptm,chai_constrained_lis,boltz_free_confidence_score,boltz_free_iptm,boltz_free_ipsae,chai_unconstrained_ipsae,boltz_free_pde,boltz_template_confidence_score,boltz_template_pdockq2,Mean_Score
0,germinal,original,0,NaN,NaN,nb_s413501_mpnn_3_PDL1,0.800253,0.3117,0.0723,0.806765,...,0.525352,0.6602,0.797495,0.558640,0.214560,0.350036,0.524040,0.876754,0.2812,0.717038
1,germinal,original,0,NaN,NaN,nb_s80903_mpnn_4_PDL1,0.706930,0.3215,0.1250,0.683231,...,0.833251,0.5909,0.860622,0.833251,0.593958,0.644546,0.367688,0.889832,0.4823,0.668711
2,germinal,original,0,NaN,NaN,nb_s185784_mpnn_4_PDL1,0.201424,0.2974,0.1291,0.306330,...,0.881156,0.2147,0.793620,0.886232,0.751587,0.693046,0.357327,0.830536,0.3102,0.343522
3,germinal,original,0,NaN,NaN,nb_s465730_mpnn_4_PDL1,0.741140,0.3291,0.1356,0.733525,...,0.613210,0.6104,0.777833,0.627241,0.234103,0.596298,0.585393,0.895193,0.5252,0.695621
4,germinal,original,0,NaN,NaN,nb_s892360_mpnn_4_PDL1,0.263522,0.4001,0.1619,0.389953,...,0.757157,0.3084,0.820556,0.790814,0.379661,0.118392,0.443887,0.926922,0.7099,0.465411

In [ ]:
# Product (Geometric approach)
df['Product_Score'] = df_norm.prod(axis=1)
df.head()

,source,type,binder,KD[M],EC50[M],sample,chai_constrained_ipsae,boltz_template_pdockq,boltz_free_pdockq,chai_constrained_interface_iptm,...,chai_constrained_lis,boltz_free_confidence_score,boltz_free_iptm,boltz_free_ipsae,chai_unconstrained_ipsae,boltz_free_pde,boltz_template_confidence_score,boltz_template_pdockq2,Mean_Score,Product_Score
0,germinal,original,0,NaN,NaN,nb_s413501_mpnn_3_PDL1,0.800253,0.3117,0.0723,0.806765,...,0.6602,0.797495,0.558640,0.214560,0.350036,0.524040,0.876754,0.2812,0.717038,0.472168
1,germinal,original,0,NaN,NaN,nb_s80903_mpnn_4_PDL1,0.706930,0.3215,0.1250,0.683231,...,0.5909,0.860622,0.833251,0.593958,0.644546,0.367688,0.889832,0.4823,0.668711,0.427448
2,germinal,original,0,NaN,NaN,nb_s185784_mpnn_4_PDL1,0.201424,0.2974,0.1291,0.306330,...,0.2147,0.793620,0.886232,0.751587,0.693046,0.357327,0.830536,0.3102,0.343522,0.096942
3,germinal,original,0,NaN,NaN,nb_s465730_mpnn_4_PDL1,0.741140,0.3291,0.1356,0.733525,...,0.6104,0.777833,0.627241,0.234103,0.596298,0.585393,0.895193,0.5252,0.695621,0.459904
4,germinal,original,0,NaN,NaN,nb_s892360_mpnn_4_PDL1,0.263522,0.4001,0.1619,0.389953,...,0.3084,0.820556,0.790814,0.379661,0.118392,0.443887,0.926922,0.7099,0.465411,0.179744

In [15]:
df.to_csv("score_combi_test.csv")

In [ ]:
# Sort by your new consensus
df = df.sort_values(by='Product_Score', ascending=False)

In [ ]:
# Note: If a score is 'lower is better', use (max - x) / (max - min)
# # normalize min max?
# direction from yaml?
def normalize(col):
    if direction == 1:
        return (col-col.min()) / (col.max() - col.min())
    else:
        return (col.max()-col) / (col.max() - col.min())

In [ ]:
# addition, multiplication of scores
# function: select 2 cols, direction, take mean 
mean = 
product =