In [1]:
import pandas as pd

snir = pd.read_csv('/scicore/home/schwede/barta0000/project/data/raw/snir/merged.csv', index_col=0)
bibs = pd.read_csv('/scicore/home/schwede/barta0000/project/data/raw/snir/260702_all_bibs_scores_w_meta_w_b2.csv', index_col=0)

bibs.head()

,sample,score_split_0,score_split_1,score_split_2,score_split_3,score_split_4,bibs_score,bibs_std,pdb_id,category,binder,heavy_chain,light_chain,antigen_chain,label,b2_ipsae
1,5ifj_abc_cut_A_D111A_model_0,0.005364,0.946642,0.716872,0.584773,0.979945,0.646719,0.394046,5ifj,mutant,0,A,B,C,Non-binder,0.906492
2,5ifj_abc_cut_A_K110A_model_0,0.004725,0.936737,0.636627,0.004650,0.652924,0.447133,0.421155,5ifj,mutant,0,A,B,C,Non-binder,0.923601
3,5ifj_abc_cut_A_S64A_model_0,0.002784,0.906196,0.866193,0.006933,0.689334,0.494288,0.454179,5ifj,mutant,0,A,B,C,Non-binder,0.895323
4,5ifj_abc_cut_A_W52A_model_0,0.000737,0.160848,0.109499,0.004070,0.265209,0.108073,0.111598,5ifj,mutant,0,A,B,C,Non-binder,0.900443
5,5ifj_abc_cut_A_Y66A_model_0,0.002818,0.416376,0.551155,0.017002,0.148354,0.227141,0.245704,5ifj,mutant,0,A,B,C,Non-binder,0.889697

In [4]:
bibs['sample'] = bibs['sample'].str.replace(r'_model_\d+$', '', regex=True)
bibs.head()

,sample,score_split_0,score_split_1,score_split_2,score_split_3,score_split_4,bibs_score,bibs_std,pdb_id,category,binder,heavy_chain,light_chain,antigen_chain,label,b2_ipsae
1,5ifj_abc_cut_A_D111A,0.005364,0.946642,0.716872,0.584773,0.979945,0.646719,0.394046,5ifj,mutant,0,A,B,C,Non-binder,0.906492
2,5ifj_abc_cut_A_K110A,0.004725,0.936737,0.636627,0.004650,0.652924,0.447133,0.421155,5ifj,mutant,0,A,B,C,Non-binder,0.923601
3,5ifj_abc_cut_A_S64A,0.002784,0.906196,0.866193,0.006933,0.689334,0.494288,0.454179,5ifj,mutant,0,A,B,C,Non-binder,0.895323
4,5ifj_abc_cut_A_W52A,0.000737,0.160848,0.109499,0.004070,0.265209,0.108073,0.111598,5ifj,mutant,0,A,B,C,Non-binder,0.900443
5,5ifj_abc_cut_A_Y66A,0.002818,0.416376,0.551155,0.017002,0.148354,0.227141,0.245704,5ifj,mutant,0,A,B,C,Non-binder,0.889697

In [6]:
bibs_clean = bibs.drop(columns=['score_split_0','score_split_1','score_split_2','score_split_3','score_split_4','bibs_std','pdb_id','category','binder','heavy_chain','light_chain','antigen_chain','label','b2_ipsae'])
bibs_clean.head()

                 sample  bibs_score
1  5ifj_abc_cut_A_D111A    0.646719
2  5ifj_abc_cut_A_K110A    0.447133
3   5ifj_abc_cut_A_S64A    0.494288
4   5ifj_abc_cut_A_W52A    0.108073
5   5ifj_abc_cut_A_Y66A    0.227141

In [10]:
bibs_clean.to_csv('/scicore/home/schwede/barta0000/project/data/raw/snir/260702_bibs_snir.csv', index=False)

In [12]:
# merge snir and bibs_clean on sample column
merged = pd.merge(snir, bibs_clean, on='sample', how='inner')
merged.head()

,type,sample,binder,KD[M],af3_pae,af3_plddt,af3_interface_dG,af3_interface_dG_SASA_ratio,af3_ipae,af3_iplddt,...,esmfold_esm3dg_dg_std,esmfold_mpnn_confidence,esmfold_mpnn_nll,esmfold_mpnn_nll_a,esmfold_mpnn_nll_b,chai_unconstrained_per_chain_ptm,chai_unconstrained_per_chain_pair_iptm,chai_constrained_per_chain_ptm,chai_constrained_per_chain_pair_iptm,bibs_score
0,original,5ifj_abc_cut,1,0.000010,2.593883,95.404666,14.690,1.855,1.993750,95.036725,...,0.247839,0.148904,1.904466,1.313454,2.495477,"[[0.9473640322685242, 0.9504183530807495, 0.17...","[[[0.9473640322685242, 0.8909199237823486, 0.0...","[[0.9454320669174194, 0.9492036700248718, 0.17...","[[[0.9454320669174194, 0.8899917602539062, 0.0...",0.604147
1,original,5ig7_abc_cut,1,0.000100,2.572969,95.599717,8.050,1.025,2.020938,94.909961,...,0.239108,0.143210,1.943453,1.315820,2.571085,"[[0.9454975724220276, 0.9490044116973877, 0.17...","[[[0.9454975724220276, 0.8908762335777283, 0.0...","[[0.9455351233482361, 0.9491659998893738, 0.17...","[[[0.9455351233482361, 0.891846776008606, 0.07...",0.527135
2,original,5ijk_acx_cut,1,0.000001,3.486349,92.439163,26.435,4.765,5.111071,69.144182,...,0.209299,0.154602,1.866932,1.099910,2.633954,"[[0.9368650317192078, 0.9511184692382812, 0.10...","[[[0.9368650317192078, 0.886062502861023, 0.01...","[[0.9452543258666992, 0.9524880051612854, 0.13...","[[[0.9452543258666992, 0.8906955122947693, 0.0...",0.840035
3,alanine_scan,5ifj_abc_cut_A_D111A,0,NaN,2.815847,95.282854,13.225,1.745,2.100000,94.730775,...,0.251839,0.157618,1.847591,1.331100,2.364081,"[[0.9472975134849548, 0.9492976665496826, 0.17...","[[[0.9472975134849548, 0.8904723525047302, 0.0...","[[0.9454193711280823, 0.9488046169281006, 0.17...","[[[0.9454193711280823, 0.8907997608184814, 0.0...",0.646719
4,alanine_scan,5ifj_abc_cut_A_K110A,0,NaN,2.790728,94.871984,19.975,2.845,2.275417,92.998114,...,0.239515,0.155875,1.858766,1.307114,2.410418,"[[0.9461949467658997, 0.9488812685012817, 0.16...","[[[0.9461949467658997, 0.8897757530212402, 0.0...","[[0.9449247717857361, 0.9489190578460693, 0.17...","[[[0.9449247717857361, 0.889130175113678, 0.07...",0.447133

In [13]:
merged.to_csv('/scicore/home/schwede/barta0000/project/data/raw/snir/merged_bibs.csv', index=False)